create or replace TABLE SEIZURES.SEIZURES.SEIZURES (
	TIMESTAMP TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	DEVICE_NAME VARCHAR(32) NOT NULL,
	DEVICE_TYPE VARCHAR(32) NOT NULL,
	SSID VARCHAR(32),
	ALTITUDE NUMBER(20,15),
	LATITUDE NUMBER(20,15) NOT NULL,
	LONGITUDE NUMBER(20,15) NOT NULL,
	ADDRESS VARCHAR(16777216),
	BATTERY NUMBER(20,15),
	BRIGHTNESS NUMBER(20,15),
	VOLUME NUMBER(20,15)
);
