# Generated by Django 5.0.3 on 2024-03-18 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(db_column='id', help_text='User identification number.', primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.SlugField(db_column='username', help_text='Username for the user account.', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3), django.core.validators.MaxLengthValidator(limit_value=16)], verbose_name='Username')),
                ('email', models.EmailField(db_column='email', default=None, help_text='E-mail address for the user account.', max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=5), django.core.validators.MaxLengthValidator(limit_value=64), django.core.validators.EmailValidator()], verbose_name='E-mail Address')),
                ('first_name', models.CharField(db_column='first_name', default=None, help_text='First name for the user account.', max_length=32, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', default=None, help_text='Last name for the user account.', max_length=32, null=True, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Date and time when the user account was created.', verbose_name='Created At')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is the user active?', verbose_name='Active?')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, help_text='Is the user staff?', verbose_name='Staff?')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, help_text='Is the user a superuser?', verbose_name='Superuser?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'db_table_comment': 'Users.',
                'ordering': ('id',),
                'managed': True,
                'default_related_name': 'user',
            },
        ),
    ]
