# Generated by Django 4.2.3 on 2023-08-01 23:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the event', primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(help_text='Device Name', max_length=32, validators=[django.core.validators.MaxLengthValidator(limit_value=32)])),
                ('device_type', models.CharField(help_text='Device Type', max_length=32, validators=[django.core.validators.MaxLengthValidator(limit_value=32)])),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address', null=True, validators=[django.core.validators.validate_ipv46_address])),
                ('ssid', models.CharField(blank=True, help_text='Optional wireless network SSID name', max_length=32, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=32)])),
                ('altitude', models.DecimalField(blank=True, decimal_places=15, help_text='Optional altitude (in feet)', max_digits=20, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
                ('latitude', models.DecimalField(decimal_places=15, help_text='GPS Latitude', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
                ('longitude', models.DecimalField(decimal_places=15, help_text='GPS Longitude', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
                ('address', models.TextField(blank=True, null=True)),
                ('battery', models.DecimalField(blank=True, decimal_places=15, help_text='Battery (between 1 and 100)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
                ('brightness', models.DecimalField(blank=True, decimal_places=15, help_text='Brightness (between 0 and 1)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
                ('volume', models.DecimalField(blank=True, decimal_places=15, help_text='Volume (between 0 and 1)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)])),
            ],
            options={
                'db_table': 'seizures',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
