# Generated by Django 4.2.4 on 2023-09-29 02:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seizures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seizure',
            name='address',
            field=models.TextField(blank=True, help_text='Address where the seizure was recorded.', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Altitude (in feet) where the seizure was recorded.', max_digits=20, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='battery',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device battery (between 1 and 100) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='Device Battery'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='brightness',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device brightness (between 0 and 1) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='Device Brightness'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='device_name',
            field=models.CharField(help_text='Name of device used to record the seizure.', max_length=32, validators=[django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='device_type',
            field=models.CharField(help_text='Type of device used to record the seizure', max_length=32, validators=[django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='latitude',
            field=models.DecimalField(decimal_places=15, help_text='GPS latitude where the seizure was recorded.', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='GPS Latitude'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='longitude',
            field=models.DecimalField(decimal_places=15, help_text='GPS longitude where the seizure was recorded.', max_digits=20, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='GPS Longitude'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='ssid',
            field=models.CharField(blank=True, help_text='Wireless network SSID detected upon seizure recording.', max_length=32, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=32)], verbose_name='Network SSID'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the seizure.', primary_key=True, serialize=False, unique=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device volume (between 0 and 1) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.DecimalValidator(decimal_places=15, max_digits=20)], verbose_name='Volume'),
        ),
    ]
