# Generated by Django 4.2.4 on 2023-08-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seizures', '0002_alter_seizure_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seizure',
            name='ip_address',
        ),
    ]
