# Generated by Django 4.2.5 on 2023-09-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seizures', '0002_alter_seizure_address_alter_seizure_altitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seizure',
            options={'managed': True, 'ordering': ('-timestamp',)},
        ),
    ]
