# Generated by Django 5.0.2 on 2024-02-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizures', '0003_alter_seizure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seizure',
            name='battery',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device battery (between 1 and 100) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20), django.core.validators.MaxValueValidator(limit_value=100), django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Device Battery'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='brightness',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device brightness (between 0 and 1) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Device Brightness'),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Device volume (between 0 and 1) upon seizure recording.', max_digits=20, null=True, validators=[django.core.validators.DecimalValidator(decimal_places=15, max_digits=20), django.core.validators.MaxValueValidator(limit_value=1), django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Volume'),
        ),
    ]
